name: CI Packages

on:
  - push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.4, 8.1, 8.2, 8.3]

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          # @todo Review which extensions are needed.
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          coverage: none

      - run: composer install --no-interaction

      - name: PhpUnit
        run: |
          set -x
          php --version
          vendor/bin/phpunit
